[workspace]
members = ["crates/store", "crates/apiserver", "crates/scheduler", "crates/kubeconfig", "crates/sentinel", "crates/sentinel-derive", "crates/proto-generated"]
resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1
debug = "line-tables-only"

[profile.dist]
inherits = "release"

[profile.dist.package.u7s-proto-generated]
opt-level = "s"
