//! Protobuf decode support for certificates.k8s.io/v1beta1 (ClusterTrustBundle,
//! PodCertificateRequest).
//!
//! Unlike every other `*_gen_adapter.rs` sibling, the `prost::Message` structs below are
//! hand-derived rather than generated by `build.rs` from a vendored `.proto` file --
//! `k8s.io/api` ships no `certificates/v1beta1/generated.proto` yet (the group is new as of
//! k8s 1.35/1.36, still ahead of the next vendored-proto refresh). Field tags are
//! transcribed directly from the upstream Go types' `protobuf:"...,N,..."` struct tags
//! (`staging/src/k8s.io/api/certificates/v1beta1/types.go`) -- the same source of truth a
//! real `.proto` file would itself be generated from -- so this stays wire-compatible with
//! client-go's protobuf codec without needing a protoc invocation. `ObjectMeta`/`Condition`/
//! `Time` are reused from the already-compiled apimachinery meta/v1 package rather than
//! redeclared.
//!
//! Because these structs never go through `build.rs`'s prost-build/protoc step, they never
//! enter the `k8s_descriptors.bin` `FileDescriptorSet` either -- so the descriptor-driven
//! field-completeness tests in `proto_descriptor.rs`/`proto_exceptions.rs` (which walk that
//! descriptor set) cannot see or enforce coverage of this group. Deliberately-unhandled
//! fields with no bearing on this bead's validation (`unverifiedUserAnnotations`,
//! `pkixPublicKey`, `proofOfPossession`, `stubPKCS10Request`) are simply omitted below
//! rather than registered anywhere.

use prost::Message;

use crate::net_disc_cert_policy_events_gen::k8s::io::apimachinery::pkg::apis::meta::v1 as meta_v1;

fn gen_object_meta_to_json(meta: meta_v1::ObjectMeta) -> serde_json::Value {
    crate::core_gen_adapter::gen_object_meta_to_json(meta)
}

/// Mirrors `resource_gen_adapter::gen_meta_condition_to_json` (private to that module, so
/// duplicated here rather than exposed crate-wide for one extra caller).
fn gen_condition_to_json(c: meta_v1::Condition) -> serde_json::Value {
    let mut m = serde_json::json!({
        "type": c.r#type.unwrap_or_default(),
        "status": c.status.unwrap_or_default(),
    });
    if let Some(v) = c.observed_generation {
        m["observedGeneration"] = v.into();
    }
    if let Some(t) = c.last_transition_time {
        if let Some(secs) = t.seconds.filter(|&s| s > 0) {
            m["lastTransitionTime"] = crate::util::secs_to_rfc3339(secs).into();
        }
    }
    if let Some(v) = c.reason.filter(|s| !s.is_empty()) {
        m["reason"] = v.into();
    }
    if let Some(v) = c.message.filter(|s| !s.is_empty()) {
        m["message"] = v.into();
    }
    m
}

fn gen_time_to_rfc3339(t: meta_v1::Time) -> Option<String> {
    t.seconds
        .filter(|&s| s > 0)
        .map(crate::util::secs_to_rfc3339)
}

// ---------------------------------------------------------------------------
// ClusterTrustBundle
// ---------------------------------------------------------------------------

#[derive(Clone, PartialEq, ::prost::Message)]
struct ClusterTrustBundleSpecProto {
    #[prost(string, optional, tag = "1")]
    signer_name: Option<String>,
    #[prost(string, optional, tag = "2")]
    trust_bundle: Option<String>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
struct ClusterTrustBundleProto {
    #[prost(message, optional, tag = "1")]
    metadata: Option<meta_v1::ObjectMeta>,
    #[prost(message, optional, tag = "2")]
    spec: Option<ClusterTrustBundleSpecProto>,
}

pub fn decode_clustertrustbundle_proto_gen(data: &[u8]) -> Option<serde_json::Value> {
    let obj = ClusterTrustBundleProto::decode(data).ok()?;
    let meta = gen_object_meta_to_json(obj.metadata.unwrap_or_default());
    let mut out = serde_json::json!({
        "apiVersion": "certificates.k8s.io/v1beta1",
        "kind": "ClusterTrustBundle",
        "metadata": meta
    });

    let spec = obj.spec.unwrap_or_default();
    let mut spec_json = serde_json::Map::new();
    if let Some(v) = spec.signer_name.filter(|s| !s.is_empty()) {
        spec_json.insert("signerName".to_string(), v.into());
    }
    if let Some(v) = spec.trust_bundle {
        spec_json.insert("trustBundle".to_string(), v.into());
    }
    out["spec"] = serde_json::Value::Object(spec_json);
    Some(out)
}

// ---------------------------------------------------------------------------
// PodCertificateRequest
// ---------------------------------------------------------------------------

#[derive(Clone, PartialEq, ::prost::Message)]
struct PodCertificateRequestSpecProto {
    #[prost(string, optional, tag = "1")]
    signer_name: Option<String>,
    #[prost(string, optional, tag = "2")]
    pod_name: Option<String>,
    #[prost(string, optional, tag = "3")]
    pod_uid: Option<String>,
    #[prost(string, optional, tag = "4")]
    service_account_name: Option<String>,
    #[prost(string, optional, tag = "5")]
    service_account_uid: Option<String>,
    #[prost(string, optional, tag = "6")]
    node_name: Option<String>,
    #[prost(string, optional, tag = "7")]
    node_uid: Option<String>,
    #[prost(int32, optional, tag = "8")]
    max_expiration_seconds: Option<i32>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
struct PodCertificateRequestStatusProto {
    #[prost(message, repeated, tag = "1")]
    conditions: Vec<meta_v1::Condition>,
    #[prost(string, optional, tag = "2")]
    certificate_chain: Option<String>,
    // Field 3 is unused upstream (types.go jumps 2 -> 4 for notBefore).
    #[prost(message, optional, tag = "4")]
    not_before: Option<meta_v1::Time>,
    #[prost(message, optional, tag = "5")]
    begin_refresh_at: Option<meta_v1::Time>,
    #[prost(message, optional, tag = "6")]
    not_after: Option<meta_v1::Time>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
struct PodCertificateRequestProto {
    #[prost(message, optional, tag = "1")]
    metadata: Option<meta_v1::ObjectMeta>,
    #[prost(message, optional, tag = "2")]
    spec: Option<PodCertificateRequestSpecProto>,
    #[prost(message, optional, tag = "3")]
    status: Option<PodCertificateRequestStatusProto>,
}

pub fn decode_podcertificaterequest_proto_gen(data: &[u8]) -> Option<serde_json::Value> {
    let obj = PodCertificateRequestProto::decode(data).ok()?;
    let meta = gen_object_meta_to_json(obj.metadata.unwrap_or_default());
    let mut out = serde_json::json!({
        "apiVersion": "certificates.k8s.io/v1beta1",
        "kind": "PodCertificateRequest",
        "metadata": meta
    });

    let spec = obj.spec.unwrap_or_default();
    let mut spec_json = serde_json::Map::new();
    macro_rules! put_str {
        ($field:expr, $key:literal) => {
            if let Some(v) = $field.filter(|s| !s.is_empty()) {
                spec_json.insert($key.to_string(), serde_json::Value::String(v));
            }
        };
    }
    put_str!(spec.signer_name, "signerName");
    put_str!(spec.pod_name, "podName");
    put_str!(spec.pod_uid, "podUID");
    put_str!(spec.service_account_name, "serviceAccountName");
    put_str!(spec.service_account_uid, "serviceAccountUID");
    put_str!(spec.node_name, "nodeName");
    put_str!(spec.node_uid, "nodeUID");
    if let Some(v) = spec.max_expiration_seconds {
        spec_json.insert("maxExpirationSeconds".to_string(), v.into());
    }
    out["spec"] = serde_json::Value::Object(spec_json);

    if let Some(status) = obj.status {
        let mut status_json = serde_json::Map::new();
        if !status.conditions.is_empty() {
            status_json.insert(
                "conditions".to_string(),
                serde_json::Value::Array(
                    status
                        .conditions
                        .into_iter()
                        .map(gen_condition_to_json)
                        .collect(),
                ),
            );
        }
        if let Some(v) = status.certificate_chain.filter(|s| !s.is_empty()) {
            status_json.insert("certificateChain".to_string(), v.into());
        }
        if let Some(t) = status.not_before.and_then(gen_time_to_rfc3339) {
            status_json.insert("notBefore".to_string(), t.into());
        }
        if let Some(t) = status.begin_refresh_at.and_then(gen_time_to_rfc3339) {
            status_json.insert("beginRefreshAt".to_string(), t.into());
        }
        if let Some(t) = status.not_after.and_then(gen_time_to_rfc3339) {
            status_json.insert("notAfter".to_string(), t.into());
        }
        if !status_json.is_empty() {
            out["status"] = serde_json::Value::Object(status_json);
        }
    }

    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Length-delimited protobuf field encoder for a raw byte payload (used to hand-build
    /// wire bytes for tests, matching the helper already used by sibling `*_gen_adapter.rs`
    /// test modules).
    fn encode_length_delimited(tag: u32, value: &[u8]) -> Vec<u8> {
        let mut out = Vec::new();
        prost::encoding::encode_key(tag, prost::encoding::WireType::LengthDelimited, &mut out);
        prost::encoding::encode_varint(value.len() as u64, &mut out);
        out.extend_from_slice(value);
        out
    }

    /// A client that submits a ClusterTrustBundle over the protobuf wire (client-go's
    /// default content-type for built-in aggregated types) must decode the same as JSON --
    /// without this decoder, `decode_proto_by_kind_and_version` falls through to raw-bytes
    /// passthrough and the create silently stores garbage instead of the real trust bundle.
    #[test]
    fn decode_clustertrustbundle_proto_gen_roundtrips_spec_fields() {
        let name = encode_length_delimited(1, b"example-bundle"); // ObjectMeta.name
        let spec = {
            let mut s = encode_length_delimited(1, b"example.com/signer"); // signerName
            s.extend_from_slice(&encode_length_delimited(2, b"PEM-DATA")); // trustBundle
            s
        };
        let mut wire = encode_length_delimited(1, &name); // ClusterTrustBundle.metadata
        wire.extend_from_slice(&encode_length_delimited(2, &spec)); // ClusterTrustBundle.spec

        let result = decode_clustertrustbundle_proto_gen(&wire)
            .expect("well-formed ClusterTrustBundle protobuf must decode");
        assert_eq!(result["kind"], "ClusterTrustBundle");
        assert_eq!(result["metadata"]["name"], "example-bundle");
        assert_eq!(result["spec"]["signerName"], "example.com/signer");
        assert_eq!(result["spec"]["trustBundle"], "PEM-DATA");
    }

    /// Same reasoning as the ClusterTrustBundle test above, but for the seven +required
    /// PodCertificateRequest spec fields a kubelet sends on create.
    #[test]
    fn decode_podcertificaterequest_proto_gen_roundtrips_required_spec_fields() {
        let name = encode_length_delimited(1, b"req-1");
        let spec = {
            let mut s = encode_length_delimited(1, b"example.com/signer"); // signerName
            s.extend_from_slice(&encode_length_delimited(2, b"my-pod")); // podName
            s.extend_from_slice(&encode_length_delimited(3, b"pod-uid-1")); // podUID
            s.extend_from_slice(&encode_length_delimited(4, b"default")); // serviceAccountName
            s.extend_from_slice(&encode_length_delimited(5, b"sa-uid-1")); // serviceAccountUID
            s.extend_from_slice(&encode_length_delimited(6, b"node-1")); // nodeName
            s.extend_from_slice(&encode_length_delimited(7, b"node-uid-1")); // nodeUID
            s
        };
        let mut wire = encode_length_delimited(1, &name);
        wire.extend_from_slice(&encode_length_delimited(2, &spec));

        let result = decode_podcertificaterequest_proto_gen(&wire)
            .expect("well-formed PodCertificateRequest protobuf must decode");
        assert_eq!(result["kind"], "PodCertificateRequest");
        assert_eq!(result["metadata"]["name"], "req-1");
        assert_eq!(result["spec"]["signerName"], "example.com/signer");
        assert_eq!(result["spec"]["podName"], "my-pod");
        assert_eq!(result["spec"]["podUID"], "pod-uid-1");
        assert_eq!(result["spec"]["serviceAccountName"], "default");
        assert_eq!(result["spec"]["serviceAccountUID"], "sa-uid-1");
        assert_eq!(result["spec"]["nodeName"], "node-1");
        assert_eq!(result["spec"]["nodeUID"], "node-uid-1");
    }
}
