use prost::Message;

use u7s_proto_generated::k8s::io::api::coordination::v1 as coord_v1;
use u7s_proto_generated::k8s::io::api::coordination::v1alpha2 as coord_v1alpha2;
use u7s_proto_generated::k8s::io::apimachinery::pkg::apis::meta::v1 as meta_v1;

// ---- shared helpers --------------------------------------------------------

fn gen_microtime_to_rfc3339(t: &meta_v1::MicroTime) -> Option<String> {
    Some(crate::core_gen_adapter::gen_microtime_fields_to_rfc3339(
        t.seconds?,
        t.nanos.unwrap_or(0),
    ))
}

fn gen_object_meta_to_json(meta: meta_v1::ObjectMeta) -> serde_json::Value {
    crate::core_gen_adapter::gen_object_meta_to_json(meta)
}

// ---- Adapter A: hand-written struct→JSON map, mirrors decode_lease_proto ----
//
// Fed by the prost-build-GENERATED Lease struct instead of the hand struct.
// Preserves the same omit-if-zero / omit-if-empty semantics as the original.
// Additionally emits strategy/preferredHolder which the original skipped.

// `gen_lease_spec_to_json`/`gen_lease_to_json` are generated by `build/codegen.rs` from the
// `.k8s.io.api.coordination.v1.LeaseSpec`/`.k8s.io.api.coordination.v1.Lease` descriptors —
// `leaseDurationSeconds`/`leaseTransitions` only emit once non-zero and `acquireTime`/`renewTime`
// delegate to the hand-written `gen_microtime_to_rfc3339` above; `metadata` delegates to
// `gen_object_meta_to_json` and `spec` delegates wholesale to `gen_lease_spec_to_json`; see
// `build/codegen.rs::lease_spec_delegated_field`/`lease_delegated_field`.
include!(concat!(env!("OUT_DIR"), "/lease_spec_gen.rs"));
include!(concat!(env!("OUT_DIR"), "/lease_gen.rs"));

pub fn decode_lease_proto_gen_a(data: &[u8]) -> Option<serde_json::Value> {
    let lease = coord_v1::Lease::decode(data).ok()?;
    let mut obj = gen_lease_to_json(lease);
    obj["apiVersion"] = "coordination.k8s.io/v1".into();
    obj["kind"] = "Lease".into();
    Some(obj)
}

// ---- LeaseCandidate (coordination.k8s.io/v1alpha2) ----
//
// CoordinatedLeaderElection candidates: namespaced, spec-only (no /status subresource — see
// upstream types.go, which declares no Status field on this type at all).

// `gen_leasecandidate_spec_to_json`/`gen_leasecandidate_to_json` are generated by
// `build/codegen.rs` from the `.k8s.io.api.coordination.v1alpha2.LeaseCandidateSpec`/
// `.k8s.io.api.coordination.v1alpha2.LeaseCandidate` descriptors — `pingTime`/`renewTime`
// delegate to the hand-written `gen_microtime_to_rfc3339` above; `metadata` delegates to
// `gen_object_meta_to_json` and `spec` delegates wholesale to `gen_leasecandidate_spec_to_json`;
// see `build/codegen.rs::leasecandidate_spec_delegated_field`/`leasecandidate_delegated_field`.
include!(concat!(env!("OUT_DIR"), "/leasecandidate_spec_gen.rs"));
include!(concat!(env!("OUT_DIR"), "/leasecandidate_gen.rs"));

pub fn decode_leasecandidate_proto_gen(data: &[u8]) -> Option<serde_json::Value> {
    let candidate = coord_v1alpha2::LeaseCandidate::decode(data).ok()?;
    let mut obj = gen_leasecandidate_to_json(candidate);
    obj["apiVersion"] = "coordination.k8s.io/v1alpha2".into();
    obj["kind"] = "LeaseCandidate".into();
    Some(obj)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test_lease_bytes() -> Vec<u8> {
        use u7s_proto_generated::k8s::io::apimachinery::pkg::apis::meta::v1 as meta_v1;
        let lease = coord_v1::Lease {
            metadata: Some(meta_v1::ObjectMeta {
                name: Some("test-lease".to_string()),
                namespace: Some("kube-system".to_string()),
                resource_version: Some("12345".to_string()),
                uid: Some("abc-123".to_string()),
                ..Default::default()
            }),
            spec: Some(coord_v1::LeaseSpec {
                holder_identity: Some("node-1".to_string()),
                lease_duration_seconds: Some(15),
                renew_time: Some(meta_v1::MicroTime {
                    seconds: Some(1_700_000_000),
                    nanos: Some(123_456_000),
                }),
                lease_transitions: Some(3),
                ..Default::default()
            }),
        };
        let mut buf = Vec::new();
        lease.encode(&mut buf).unwrap();
        buf
    }

    fn make_test_lease_bytes_with_alpha_fields() -> Vec<u8> {
        use u7s_proto_generated::k8s::io::apimachinery::pkg::apis::meta::v1 as meta_v1;
        let lease = coord_v1::Lease {
            metadata: Some(meta_v1::ObjectMeta {
                name: Some("coordinated-lease".to_string()),
                namespace: Some("kube-system".to_string()),
                ..Default::default()
            }),
            spec: Some(coord_v1::LeaseSpec {
                holder_identity: Some("candidate-a".to_string()),
                lease_duration_seconds: Some(10),
                strategy: Some("OldestEmulationVersion".to_string()),
                preferred_holder: Some("candidate-b".to_string()),
                ..Default::default()
            }),
        };
        let mut buf = Vec::new();
        lease.encode(&mut buf).unwrap();
        buf
    }

    #[test]
    fn decode_lease_proto_gen_a_emits_required_fields_for_leader_election() {
        let bytes = make_test_lease_bytes();
        let gen_a = decode_lease_proto_gen_a(&bytes).expect("Lease decode must succeed");

        assert_eq!(
            gen_a["apiVersion"], "coordination.k8s.io/v1",
            "apiVersion must be coordination.k8s.io/v1: kubectl uses this to route the object"
        );
        assert_eq!(
            gen_a["kind"], "Lease",
            "kind must be Lease: missing kind breaks server-side apply"
        );
        assert_eq!(
            gen_a["metadata"]["name"], "test-lease",
            "metadata.name must survive: name is the primary object identifier"
        );
        assert_eq!(
            gen_a["metadata"]["namespace"], "kube-system",
            "metadata.namespace must survive: wrong namespace routes to wrong store"
        );
        assert_eq!(
            gen_a["spec"]["holderIdentity"], "node-1",
            "holderIdentity must survive: Lease holder is the core semantics"
        );
        assert_eq!(
            gen_a["spec"]["leaseDurationSeconds"], 15,
            "leaseDurationSeconds must survive: governs leader election timeout"
        );
        assert!(
            gen_a["spec"]["renewTime"].is_string(),
            "renewTime MicroTime must be emitted: nanos precision required for leader election"
        );
        assert_eq!(
            gen_a["spec"]["leaseTransitions"], 3,
            "leaseTransitions must survive: clients use this to detect leader churn"
        );
    }

    #[test]
    fn decode_lease_proto_gen_a_emits_alpha_fields_strategy_and_preferred_holder() {
        let bytes = make_test_lease_bytes_with_alpha_fields();
        let gen_a = decode_lease_proto_gen_a(&bytes).expect("Lease decode must succeed");

        assert_eq!(
            gen_a["spec"]["strategy"], "OldestEmulationVersion",
            "strategy must be emitted: generated struct covers all fields by construction, \
             hand struct silently dropped this field causing coordinated leader election to break"
        );
        assert_eq!(
            gen_a["spec"]["preferredHolder"], "candidate-b",
            "preferredHolder must be emitted: generated struct covers all fields by construction"
        );
    }

    #[test]
    fn generated_lease_spec_covers_all_proto_fields_by_construction() {
        use u7s_proto_generated::k8s::io::api::coordination::v1::LeaseSpec;
        let spec = LeaseSpec {
            holder_identity: Some("x".to_string()),
            lease_duration_seconds: Some(1),
            acquire_time: None,
            renew_time: None,
            lease_transitions: Some(0),
            strategy: Some("y".to_string()),
            preferred_holder: Some("z".to_string()),
        };
        let mut buf = Vec::new();
        spec.encode(&mut buf).unwrap();
        let decoded = LeaseSpec::decode(buf.as_slice()).unwrap();
        assert_eq!(
            decoded.strategy.as_deref(),
            Some("y"),
            "strategy field must survive round-trip: it's present in generated struct by \
             construction, not by authoring discipline"
        );
        assert_eq!(
            decoded.preferred_holder.as_deref(),
            Some("z"),
            "preferredHolder field must survive round-trip: present in generated struct by \
             construction"
        );
    }

    // ---- Sentinel completeness: decode_lease_proto_gen_a ----
    //
    // Builds a Lease with every metadata/spec field set to a value no zero/empty-elision check
    // in gen_object_meta_to_json or decode_lease_proto_gen_a could mistake for "unset" (see
    // u7s_sentinel::Sentinel), decodes it through the real decode_lease_proto_gen_a entry point,
    // and asserts every field name shows up somewhere in the resulting JSON. A name that never
    // appears means this file's gen_object_meta_to_json (a near-duplicate of
    // core_gen_adapter's, not shared code) or decode_lease_proto_gen_a never reads that field
    // from the decoded protobuf struct at all.

    use std::collections::BTreeSet;
    use u7s_sentinel::Sentinel;

    use crate::util::sentinel_test_util::{assert_fields_present, collect_leaf_paths};

    #[test]
    fn sentinel_completeness_decode_lease_proto_gen_a() {
        use u7s_proto_generated::k8s::io::apimachinery::pkg::apis::meta::v1 as meta_v1;
        let lease = coord_v1::Lease {
            metadata: Some(meta_v1::ObjectMeta::sentinel()),
            spec: Some(coord_v1::LeaseSpec::sentinel()),
        };
        let mut buf = Vec::new();
        lease.encode(&mut buf).unwrap();
        let decoded = decode_lease_proto_gen_a(&buf)
            .expect("sentinel Lease must decode via the generated path");

        let mut paths = BTreeSet::new();
        collect_leaf_paths(&decoded, "", &mut paths);

        // Derived from the .proto schema rather than hand-listed, so a field added upstream is
        // demanded here automatically instead of when someone remembers to type it. The
        // deliberate omissions (selfLink) and the currently-tolerated real drops
        // (deletionTimestamp/deletionGracePeriodSeconds/managedFields) live in one reviewed table
        // in `proto_descriptor`, not in a comment in each of the twelve adapter test modules.
        let expected = crate::proto_descriptor::expected_json_keys_for(&[
            ".k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta",
            ".k8s.io.api.coordination.v1.LeaseSpec",
        ]);
        let expected: Vec<&str> = expected.iter().map(String::as_str).collect();
        assert_fields_present(&paths, &expected);
    }

    // ---- Field-omission: decode_lease_proto_gen_a with an all-default Lease ----
    //
    // A Lease with every optional field unset must decode to a `spec`-less object, and
    // metadata must carry no explicit nulls besides `creationTimestamp` (which upstream
    // `metav1.Time` always marshals as `null` when zero). A stray `"holderIdentity": null` or a
    // `"spec": null` would make a leader-election client think a lease was actively released by
    // some holder instead of never having been acquired at all — those are different states.

    use crate::util::sentinel_test_util::assert_no_stray_nulls;

    #[test]
    fn decode_lease_proto_gen_a_omits_unset_fields_instead_of_emitting_null() {
        let lease = coord_v1::Lease::default();
        let mut buf = Vec::new();
        lease.encode(&mut buf).unwrap();
        let decoded = decode_lease_proto_gen_a(&buf).expect("all-default Lease must still decode");

        assert_no_stray_nulls(&decoded, &["creationTimestamp"]);
        assert!(
            decoded.get("spec").is_none(),
            "an unset LeaseSpec must omit `spec` entirely, not emit `spec: null` or `spec: {{}}` \
             — a present-but-empty spec could be misread as \"lease held with no identity\""
        );
    }

    // ---- LeaseCandidate (coordination.k8s.io/v1alpha2) ----

    fn make_test_leasecandidate_bytes() -> Vec<u8> {
        let candidate = coord_v1alpha2::LeaseCandidate {
            metadata: Some(meta_v1::ObjectMeta {
                name: Some("candidate-a".to_string()),
                namespace: Some("kube-system".to_string()),
                resource_version: Some("42".to_string()),
                uid: Some("cand-uid-1".to_string()),
                ..Default::default()
            }),
            spec: Some(coord_v1alpha2::LeaseCandidateSpec {
                lease_name: Some("apiserver-leader".to_string()),
                binary_version: Some("1.36.0".to_string()),
                emulation_version: Some("1.35.0".to_string()),
                strategy: Some("OldestEmulationVersion".to_string()),
                renew_time: Some(meta_v1::MicroTime {
                    seconds: Some(1_700_000_000),
                    nanos: Some(123_456_000),
                }),
                ..Default::default()
            }),
        };
        let mut buf = Vec::new();
        candidate.encode(&mut buf).unwrap();
        buf
    }

    /// CoordinatedLeaderElection picks a winner by comparing `leaseName`/`binaryVersion`/
    /// `strategy` across every candidate for a Lease; if any of those three drop on decode,
    /// the scheduler/controller-manager leader election either can't find its own candidate
    /// object or silently applies the wrong tie-break strategy.
    #[test]
    fn decode_leasecandidate_proto_gen_emits_fields_leader_election_compares() {
        let bytes = make_test_leasecandidate_bytes();
        let decoded =
            decode_leasecandidate_proto_gen(&bytes).expect("LeaseCandidate decode must succeed");

        assert_eq!(
            decoded["apiVersion"], "coordination.k8s.io/v1alpha2",
            "apiVersion must be coordination.k8s.io/v1alpha2: kubectl/client-go route on it"
        );
        assert_eq!(decoded["kind"], "LeaseCandidate");
        assert_eq!(decoded["metadata"]["name"], "candidate-a");
        assert_eq!(decoded["metadata"]["namespace"], "kube-system");
        assert_eq!(
            decoded["spec"]["leaseName"], "apiserver-leader",
            "leaseName must survive: it's how a candidate is matched to the Lease it contends for"
        );
        assert_eq!(
            decoded["spec"]["binaryVersion"], "1.36.0",
            "binaryVersion must survive: coordinated leader election tie-breaks on it"
        );
        assert_eq!(
            decoded["spec"]["emulationVersion"], "1.35.0",
            "emulationVersion must survive: required whenever strategy is OldestEmulationVersion"
        );
        assert_eq!(
            decoded["spec"]["strategy"], "OldestEmulationVersion",
            "strategy must survive: determines which candidate's vote wins on conflict"
        );
        assert!(
            decoded["spec"]["renewTime"].is_string(),
            "renewTime MicroTime must be emitted: garbage collection of stale candidates depends \
             on it"
        );
    }

    #[test]
    fn generated_leasecandidate_spec_covers_all_proto_fields_by_construction() {
        let spec = coord_v1alpha2::LeaseCandidateSpec {
            lease_name: Some("x".to_string()),
            ping_time: None,
            renew_time: None,
            binary_version: Some("1.0.0".to_string()),
            emulation_version: Some("1.0.0".to_string()),
            strategy: Some("y".to_string()),
        };
        let mut buf = Vec::new();
        spec.encode(&mut buf).unwrap();
        let decoded = coord_v1alpha2::LeaseCandidateSpec::decode(buf.as_slice()).unwrap();
        assert_eq!(
            decoded.strategy.as_deref(),
            Some("y"),
            "strategy field must survive round-trip: present in the generated struct by \
             construction, not by authoring discipline"
        );
    }

    // ---- Sentinel completeness: decode_leasecandidate_proto_gen ----
    //
    // Same rationale as `sentinel_completeness_decode_lease_proto_gen_a` above: builds a
    // fully-populated LeaseCandidate, decodes it through the real entry point, and asserts every
    // schema field reaches the JSON — so a field added upstream (or dropped from this adapter)
    // fails a test instead of silently missing from kubectl's view of leader-election state.
    #[test]
    fn sentinel_completeness_decode_leasecandidate_proto_gen() {
        let candidate = coord_v1alpha2::LeaseCandidate {
            metadata: Some(meta_v1::ObjectMeta::sentinel()),
            spec: Some(coord_v1alpha2::LeaseCandidateSpec::sentinel()),
        };
        let mut buf = Vec::new();
        candidate.encode(&mut buf).unwrap();
        let decoded = decode_leasecandidate_proto_gen(&buf)
            .expect("sentinel LeaseCandidate must decode via the generated path");

        let mut paths = BTreeSet::new();
        collect_leaf_paths(&decoded, "", &mut paths);

        let expected = crate::proto_descriptor::expected_json_keys_for(&[
            ".k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta",
            ".k8s.io.api.coordination.v1alpha2.LeaseCandidateSpec",
        ]);
        let expected: Vec<&str> = expected.iter().map(String::as_str).collect();
        assert_fields_present(&paths, &expected);
    }

    // ---- Field-omission: decode_leasecandidate_proto_gen with an all-default LeaseCandidate ----
    //
    // Mirrors `decode_lease_proto_gen_a_omits_unset_fields_instead_of_emitting_null`: an unset
    // spec must omit `spec` entirely rather than emit `spec: null`/`spec: {{}}`, since a
    // present-but-empty spec could be misread as "candidate with no leaseName/strategy" instead
    // of "candidate object not yet fully populated."
    #[test]
    fn decode_leasecandidate_proto_gen_omits_unset_fields_instead_of_emitting_null() {
        let candidate = coord_v1alpha2::LeaseCandidate::default();
        let mut buf = Vec::new();
        candidate.encode(&mut buf).unwrap();
        let decoded = decode_leasecandidate_proto_gen(&buf)
            .expect("all-default LeaseCandidate must still decode");

        assert_no_stray_nulls(&decoded, &["creationTimestamp"]);
        assert!(
            decoded.get("spec").is_none(),
            "an unset LeaseCandidateSpec must omit `spec` entirely, not emit `spec: null` or \
             `spec: {{}}`"
        );
    }

    // ---- Byte-identical audit: codegen migration (Phase 4.10) ----
    //
    // Reconstructs the pre-migration hand-written `decode_lease_proto_gen_a`/
    // `decode_leasecandidate_proto_gen` verbatim (they called the exact same
    // `gen_object_meta_to_json`/`gen_microtime_to_rfc3339` helpers this migration left
    // untouched) and diffs their output against the codegen-generated `gen_lease_to_json`/
    // `gen_leasecandidate_to_json` this migration installed. A wrong field name, a missing
    // `!= 0` guard on `leaseDurationSeconds`/`leaseTransitions`, or a dropped MicroTime delegate
    // in `build/codegen.rs` would show up here as a JSON mismatch — leader election silently
    // misreading a lease's holder/renewal state is exactly the failure mode a byte-for-byte diff
    // against the known-good pre-migration output catches.
    #[test]
    fn codegen_migration_lease_family_matches_pre_migration_hand_written_output() {
        fn old_decode_lease_proto_gen_a(data: &[u8]) -> Option<serde_json::Value> {
            let lease = coord_v1::Lease::decode(data).ok()?;
            let meta = gen_object_meta_to_json(lease.metadata.unwrap_or_default());

            let mut obj = serde_json::json!({
                "apiVersion": "coordination.k8s.io/v1",
                "kind": "Lease",
                "metadata": meta
            });

            if let Some(spec) = lease.spec {
                let mut spec_map = serde_json::Map::new();
                if let Some(v) = spec.holder_identity.filter(|s| !s.is_empty()) {
                    spec_map.insert("holderIdentity".to_string(), serde_json::Value::String(v));
                }
                if let Some(v) = spec.lease_duration_seconds.filter(|&n| n != 0) {
                    spec_map.insert(
                        "leaseDurationSeconds".to_string(),
                        serde_json::Value::Number(v.into()),
                    );
                }
                if let Some(t) = spec.acquire_time.as_ref() {
                    if let Some(ts) = gen_microtime_to_rfc3339(t) {
                        spec_map.insert("acquireTime".to_string(), serde_json::Value::String(ts));
                    }
                }
                if let Some(t) = spec.renew_time.as_ref() {
                    if let Some(ts) = gen_microtime_to_rfc3339(t) {
                        spec_map.insert("renewTime".to_string(), serde_json::Value::String(ts));
                    }
                }
                if let Some(v) = spec.lease_transitions.filter(|&n| n != 0) {
                    spec_map.insert(
                        "leaseTransitions".to_string(),
                        serde_json::Value::Number(v.into()),
                    );
                }
                if let Some(v) = spec.strategy.filter(|s| !s.is_empty()) {
                    spec_map.insert("strategy".to_string(), serde_json::Value::String(v));
                }
                if let Some(v) = spec.preferred_holder.filter(|s| !s.is_empty()) {
                    spec_map.insert("preferredHolder".to_string(), serde_json::Value::String(v));
                }
                if !spec_map.is_empty() {
                    obj["spec"] = serde_json::Value::Object(spec_map);
                }
            }

            Some(obj)
        }

        fn old_decode_leasecandidate_proto_gen(data: &[u8]) -> Option<serde_json::Value> {
            let candidate = coord_v1alpha2::LeaseCandidate::decode(data).ok()?;
            let meta = gen_object_meta_to_json(candidate.metadata.unwrap_or_default());

            let mut obj = serde_json::json!({
                "apiVersion": "coordination.k8s.io/v1alpha2",
                "kind": "LeaseCandidate",
                "metadata": meta
            });

            if let Some(spec) = candidate.spec {
                let mut spec_map = serde_json::Map::new();
                if let Some(v) = spec.lease_name.filter(|s| !s.is_empty()) {
                    spec_map.insert("leaseName".to_string(), serde_json::Value::String(v));
                }
                if let Some(t) = spec.ping_time.as_ref() {
                    if let Some(ts) = gen_microtime_to_rfc3339(t) {
                        spec_map.insert("pingTime".to_string(), serde_json::Value::String(ts));
                    }
                }
                if let Some(t) = spec.renew_time.as_ref() {
                    if let Some(ts) = gen_microtime_to_rfc3339(t) {
                        spec_map.insert("renewTime".to_string(), serde_json::Value::String(ts));
                    }
                }
                if let Some(v) = spec.binary_version.filter(|s| !s.is_empty()) {
                    spec_map.insert("binaryVersion".to_string(), serde_json::Value::String(v));
                }
                if let Some(v) = spec.emulation_version.filter(|s| !s.is_empty()) {
                    spec_map.insert("emulationVersion".to_string(), serde_json::Value::String(v));
                }
                if let Some(v) = spec.strategy.filter(|s| !s.is_empty()) {
                    spec_map.insert("strategy".to_string(), serde_json::Value::String(v));
                }
                if !spec_map.is_empty() {
                    obj["spec"] = serde_json::Value::Object(spec_map);
                }
            }

            Some(obj)
        }

        // Every field set to a value no zero/empty-elision check could mistake for "unset"
        // (Sentinel's own contract), so the audit exercises `leaseDurationSeconds`/
        // `leaseTransitions`'s `!= 0` guards and both MicroTime fields' RFC3339 delegate, not
        // just the plain-string fields a less thorough fixture would happen to cover.
        let lease = coord_v1::Lease {
            metadata: Some(meta_v1::ObjectMeta {
                name: Some("audit-lease".to_string()),
                namespace: Some("kube-system".to_string()),
                ..Default::default()
            }),
            spec: Some(coord_v1::LeaseSpec::sentinel()),
        };
        let mut lease_bytes = Vec::new();
        lease.encode(&mut lease_bytes).unwrap();
        assert_eq!(
            old_decode_lease_proto_gen_a(&lease_bytes),
            decode_lease_proto_gen_a(&lease_bytes),
            "codegen-generated decode_lease_proto_gen_a must match the pre-migration \
             hand-written decoder field-for-field — any divergence here is a silent \
             leader-election-observable field drop introduced by the Phase 4.10 migration"
        );

        // A Lease with a present-but-all-zero/empty spec must still omit the `spec` key
        // entirely (not `spec: {{}}`) — the pre-migration decoder's own `!spec_map.is_empty()`
        // guard, which the generated `gen_lease_spec_to_json`/`lease_delegated_field`'s `spec`
        // entry must replicate rather than just mechanically inserting `Some(LeaseSpec::default())`.
        let empty_spec_lease = coord_v1::Lease {
            metadata: Some(meta_v1::ObjectMeta::default()),
            spec: Some(coord_v1::LeaseSpec::default()),
        };
        let mut empty_spec_bytes = Vec::new();
        empty_spec_lease.encode(&mut empty_spec_bytes).unwrap();
        assert_eq!(
            old_decode_lease_proto_gen_a(&empty_spec_bytes),
            decode_lease_proto_gen_a(&empty_spec_bytes),
            "a Lease with a present-but-empty LeaseSpec must still omit `spec` entirely, \
             matching the pre-migration decoder exactly"
        );

        let candidate = coord_v1alpha2::LeaseCandidate {
            metadata: Some(meta_v1::ObjectMeta {
                name: Some("audit-candidate".to_string()),
                namespace: Some("kube-system".to_string()),
                ..Default::default()
            }),
            spec: Some(coord_v1alpha2::LeaseCandidateSpec::sentinel()),
        };
        let mut candidate_bytes = Vec::new();
        candidate.encode(&mut candidate_bytes).unwrap();
        assert_eq!(
            old_decode_leasecandidate_proto_gen(&candidate_bytes),
            decode_leasecandidate_proto_gen(&candidate_bytes),
            "codegen-generated decode_leasecandidate_proto_gen must match the pre-migration \
             hand-written decoder field-for-field"
        );
    }
}
